CIVILIANS = 'civilians'
MAFIA = 'mafia'
DETECTIVE = 'detective'
PUTANA = 'putana'
MANIAC = 'maniac'
DOCTOR = 'doctor'
ROLES = {
    5: {CIVILIANS: 3, MAFIA: 1, DETECTIVE:1},
    6: {CIVILIANS: 3, MAFIA: 1, DETECTIVE:1, PUTANA:1},
    7: {CIVILIANS: 3, MAFIA: 2, DETECTIVE:1, PUTANA:1},
    8: {CIVILIANS: 4, MAFIA: 2, DETECTIVE:1, PUTANA:1},
    9: {CIVILIANS: 4, MAFIA: 2, DETECTIVE:1, PUTANA:1, DOCTOR: 1},
    10: {CIVILIANS: 4, MAFIA: 2, DETECTIVE:1, PUTANA:1, DOCTOR: 1, MANIAC: 1},
    11: {CIVILIANS: 4, MAFIA: 3, DETECTIVE:1, PUTANA:1, DOCTOR: 1, MANIAC: 1},
}